services:
  homepage:
    build: .
    volumes:
      - ./static:/usr/share/nginx/html/static:ro
    ports:
      - ${FRONT_PORT}:3000
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    external: true
